version: '3.9'
services:
    loki:
        image: grafana/loki:2.8.0
        container_name: loki
        ports:
            - 3100:3100
        volumes:
            - loki-data:/loki
        networks:
            - elastic

    grafana:
        image: grafana/grafana:9.5.0
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - 3200:3200
        networks:
            - elastic
        depends_on:
            - loki

volumes:
    loki-data:
        driver: local

networks:
    elastic:
        driver: bridge
