version: '3.9'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=elasticsearch-cluster
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
            - 9200:9200
        volumes:
            - data:/usr/share/elasticsearch/data
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:8.9.1
        container_name: kibana
        environment:
            - node.name=kibana
            - cluster.name=elasticsearch-cluster
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        networks:
            - elastic
        depends_on:
            - elasticsearch

volumes:
    data:
        driver: local

networks:
    elastic:
        driver: bridge
